'use strict'

function getImgsFromDB() {
  return [
    //1 Trump Angry
    {
      id: generateRandomID(),
      url: `img/${1}.jpg`,
      keywords: [
        'angry',
        'man',
        'pointing',
        'yelling',
        'political',
        'trump',
        'serious',
        'speech',
        'president',
        'reaction',
      ],
    }, //2 Maria in Field (The Sound of Music)
    {
      id: generateRandomID(),
      url: `img/${2}.jpg`,
      keywords: [
        'happy',
        'woman',
        'singing',
        'field',
        'mountain',
        'joy',
        'freedom',
        'classic',
        'arms wide',
        'dramatic',
      ],
    }, //3 Baby and Puppy Sleeping
    {
      id: generateRandomID(),
      url: `img/${3}.jpg`,
      keywords: [
        'cute',
        'sleeping',
        'baby',
        'puppy',
        'dog',
        'animal',
        'friends',
        'cozy',
        'nap',
        'aww',
      ],
    }, //4 Cat on Laptop
    {
      id: generateRandomID(),
      url: `img/${4}.jpg`,
      keywords: [
        'cat',
        'sleeping',
        'laptop',
        'animal',
        'lazy',
        'tired',
        'work',
        'distraction',
        'keyboard',
        'cute',
      ],
    }, //5 Success Kid
    {
      id: generateRandomID(),
      url: `img/${5}.jpg`,
      keywords: [
        'happy',
        'baby',
        'kid',
        'success',
        'fist pump',
        'win',
        'beach',
        'determined',
        'triumph',
        'achievement',
      ],
    }, //6 Ancient Aliens Guy (Giorgio A. Tsoukalos)
    {
      id: generateRandomID(),
      url: `img/${6}.jpg`,
      keywords: [
        'man',
        'explaining',
        'aliens',
        'conspiracy',
        'crazy hair',
        'theory',
        'unbelievable',
        'history',
        'science',
        'sure',
      ],
    }, //7 Surprised Baby (Wide Eyes)
    {
      id: generateRandomID(),
      url: `img/${7}.jpg`,
      keywords: [
        'shocked',
        'baby',
        'surprised',
        'confused',
        'wide eyes',
        'scared',
        'gasp',
        'reaction',
        'kid',
        'oh my god',
      ],
    }, //8 Willy Wonka (Gene Wilder)
    {
      id: generateRandomID(),
      url: `img/${8}.jpg`,
      keywords: [
        'sarcastic',
        'man',
        'smug',
        'willy wonka',
        'amused',
        'condescending',
        'snarky',
        'purple',
        'top hat',
        'classic',
      ],
    }, //9 Evil Plotting Baby (Rubbing Hands)
    {
      id: generateRandomID(),
      url: `img/${9}.jpg`,
      keywords: [
        'evil',
        'baby',
        'plotting',
        'laughing',
        'rubbing hands',
        'scheme',
        'villain',
        'mischievous',
        'funny',
        'kid',
      ],
    }, //10 Obama Laughing
    {
      id: generateRandomID(),
      url: `img/${10}.jpg`,
      keywords: [
        'happy',
        'laughing',
        'man',
        'obama',
        'president',
        'hilarious',
        'reaction',
        'cringe',
        'smile',
        'funny',
      ],
    }, //11 Basketball Players Kissing (Awkward Hug)
    {
      id: generateRandomID(),
      url: `img/${11}.jpg`,
      keywords: [
        'awkward',
        'kiss',
        'men',
        'sports',
        'basketball',
        'funny',
        'fail',
        'hug',
        'close up',
        'bromance',
      ],
    }, //12 Pointing Man in Glasses (Gotcha)
    {
      id: generateRandomID(),
      url: `img/${12}.jpg`,
      keywords: [
        'serious',
        'man',
        'pointing',
        'glasses',
        'older',
        'professor',
        'host',
        'gotcha',
        'accusing',
        'i see you',
      ],
    }, //13 Gatsby Toast (Leonardo DiCaprio)
    {
      id: generateRandomID(),
      url: `img/${13}.jpg`,
      keywords: [
        'happy',
        'man',
        'cheers',
        'toast',
        'celebration',
        'gatsby',
        'leonardo',
        'party',
        'fancy',
        'smiling',
      ],
    }, //14 Morpheus from The Matrix
    {
      id: generateRandomID(),
      url: `img/${14}.jpg`,
      keywords: [
        'serious',
        'man',
        'matrix',
        'morpheus',
        'shades',
        'cool',
        'movie',
        'scifi',
        'sunglasses',
        'what if',
      ],
    }, //15 Boromir (One Does Not Simply)
    {
      id: generateRandomID(),
      url: `img/${15}.jpg`,
      keywords: [
        'serious',
        'man',
        'boromir',
        'lord of the rings',
        'one does not simply',
        'fantasy',
        'movie',
        'epic',
        'dramatic',
        'hand',
      ],
    }, //16 Captain Picard Facepalm
    {
      id: generateRandomID(),
      url: `img/${16}.jpg`,
      keywords: [
        'embarrassed',
        'man',
        'facepalm',
        'awkward',
        'cringe',
        'smug',
        'disappointed',
        'star trek',
        'picard',
        'professor',
      ],
    }, //17 Woody and Buzz Staring
    {
      id: generateRandomID(),
      url: `img/${17}.jpg`,
      keywords: [
        'unimpressed',
        'toy story',
        'woody',
        'buzz',
        'disbelief',
        'staring',
        'cartoon',
        'movie',
        'reaction',
        'two guys',
      ],
    }, //18 Putin Hand Gesture (Serious)
    {
      id: generateRandomID(),
      url: `img/${18}.jpg`,
      keywords: [
        'serious',
        'man',
        'putin',
        'politician',
        'speaking',
        'formal',
        'explaining',
        'counting',
        'russia',
        'hand',
      ],
    }, //19 Pauly D/Jersey Shore Shocked
    {
      id: generateRandomID(),
      url: `img/${19}.jpg`,
      keywords: [
        'shocked',
        'man',
        'surprised',
        'screaming',
        'gasp',
        'reaction',
        'jersey shore',
        'pauly d',
        'reality tv',
        'oh no',
      ],
    }, //20 Ancient Aliens Guy (Second image)
    {
      id: generateRandomID(),
      url: `img/${20}.jpg`,
      keywords: [
        'man',
        'explaining',
        'aliens',
        'conspiracy',
        'crazy hair',
        'theory',
        'unbelievable',
        'history',
        'science',
        'sure',
      ],
    }, //21 Dr. Evil Peace Sign (Mike Myers)
    {
      id: generateRandomID(),
      url: `img/${21}.jpg`,
      keywords: [
        'funny',
        'man',
        'dr evil',
        'austin powers',
        'peace sign',
        'villain',
        'bald',
        'plotting',
        'movie',
        'satire',
      ],
    }, //22 Puppies Kissing (Labradors)
    {
      id: generateRandomID(),
      url: `img/${22}.jpg`,
      keywords: [
        'cute',
        'puppies',
        'dogs',
        'animals',
        'kissing',
        'licking',
        'love',
        'aww',
        'labrador',
        'best friends',
      ],
    }, //23: Dancing Kids
    {
      id: generateRandomID(),
      url: `img/${23}.jpg`,
      keywords: [
        'happy',
        'kids',
        'dancing',
        'celebration',
        'triumph',
        'victory',
        'funny',
        'joyful',
        'group',
        'winning',
      ],
    }, //24: Donald Trump Pointing/Angry
    {
      id: generateRandomID(),
      url: `img/${24}.jpg`,
      keywords: [
        'angry',
        'man',
        'pointing',
        'trump',
        'speech',
        'mad',
        'serious',
        'president',
        'political',
        'reaction',
      ],
    }, //25: French Bulldog Puppy Stretching
    {
      id: generateRandomID(),
      url: `img/${25}.jpg`,
      keywords: [
        'cute',
        'dog',
        'puppy',
        'french bulldog',
        'stretching',
        'animal',
        'funny',
        'yoga',
        'awkward',
        'floor',
      ],
    }, //26: Oprah Winfrey Excited
    {
      id: generateRandomID(),
      url: `img/${26}.jpg`,
      keywords: [
        'happy',
        'woman',
        'excited',
        'oprah',
        'screaming',
        'celebration',
        'arms wide',
        'mic',
        'talk show',
        'reaction',
      ],
    },
  ]
}

function getTextFromDB() {
  return [
    'This is fine',
    'Living my worst life',
    'Please stop talking',
    'I need sleep',
    'Not my problem',
    'Why am I like this',
    'Current emotional status',
    'Try me today',
    'I can’t even',
    'Mentally not present',
    'Guess who’s back',
    'Zero thoughts given',
    "This ain't it",
    'Do not disturb',
    'Running on chaos',
    'My last braincell',
    'Everything is burning',
    'Please send snacks',
    'Too early for this',
    'Who approved this',
    'Certified disaster moment',
    'Peak procrastination vibes',
    'Don’t ask why',
    'Overthinking in progress',
    'Absolutely not today',
  ]
}
